# Changes here will be overwritten by Copier
_commit: v0.1.2
_src_path: gh:msharp9/copy-pasta
description: A digital implementation of the party game 1000 Blank White Cards, where
    players draw, write, and play their own cards to invent the game as they go.
name: a-thousand-blank-white-cards
